# Generated by Django 2.1.3 on 2018-11-14 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assist', '0006_auto_20181018_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='order_Num',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
